### ISSUE TITLE
Makefile:2: *** missing separator.  Stop.

### ISSUE THREAD

**Issue by jeffreys-cat** [spa5k/nextjs_approuter_electron#1]
- Makefile:2: *** missing separator.  Stop.

**Comment by jeffreys-cat** [comment]
in apps/electron folder, i run the `npm run dist`, but the dmg is not work

![image](https://github.com/spa5k/nextjs_approuter_electron/assets/11832969/6e8531ea-c543-4436-b32f-c1444f9195f1)

**Comment by spa5k** [comment]
Hey, thanks for the bugs, for the first one, looks like some formatting issue in makefile, and for the second, don't have a macbook in hand, so can't fix it.

Its probably related to how it's packaging, which I belive its missing the plist related files that MacOs needs, so if you please check another electron repo that has it there, and fix this one. Thanks.

**Comment by spa5k** [comment]
Makefile has been fixed, for it to run in apple, you need to setup lots of things like Notarization, take a look here- 

https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/main/package.json

**Comment by kody435** [comment]
@jeffreys-cat Were you able to solve NextJSElectron quit unexpectedly error?

@spa5k Can you make separate makefile for npm ?

**Comment by spa5k** [comment]
wdym? If you check package.json, it has all scripts - 

```
    "next:dev": "next dev",
    "next:build": "next build",
    "next:start": "next start",
    "next:lint": "next lint",
    "format": "dprint fmt",
    "postinstall": "electron-builder install-app-deps",
    "electron:dist": "electron-builder --dir",
    "electron:dist:deb": "electron-builder --linux deb",
    "electron:build": "tsup",
    "build": "run-s next:build electron:build",
    "dist": "run-s build electron:dist",
    "dev": "npm-run-all --parallel electron:dev next:dev",
    "electron:build_watch": "tsup --watch",
    "electron:dev": "npm-run-all --parallel electron:build_watch electron:watch",
    "electron:watch": "cross-env NODE_ENV='development' nodemon"
```

And that error is because the code is not signed, macOS requires a Developer certificate worth $100 per year, at least that is my guess, no access to mac rn. 

https://github.com/spa5k/Siraat/releases/tag/v0.0.4-alpha.2


Check the produced DMG file here and see if it's working in mac.

**Comment by kody435** [comment]
<img width="819" alt="Screenshot 2024-09-18 at 15 16 29" src="https://github.com/user-attachments/assets/9bb868a2-f681-4544-8bdb-2904b65968a0">
<img width="520" alt="Screenshot 2024-09-18 at 15 21 46" src="https://github.com/user-attachments/assets/6df0f139-04bd-47a8-8bd1-d0b19ee6b756">

## I am getting this errors while I was trying to install this softwares
[siraat-0.0.4-alpha.2.dmg](https://github.com/spa5k/Siraat/releases/download/v0.0.4-alpha.2/siraat-0.0.4-alpha.2.dmg)
[siraat-0.0.4-alpha.2-arm64.dmg](https://github.com/spa5k/Siraat/releases/download/v0.0.4-alpha.2/siraat-0.0.4-alpha.2-arm64.dmg)

**Comment by spa5k** [comment]
```
"mac": {
      "identity": null,
      "target": [
        {
          "target": "dmg",
          "arch": [
            "x64",
            "arm64"
          ]
        }
      ]
      ```
      
      
      In package.json of the siraat, i've mentioned these, try adding yours here, then build the app again

**Comment by spa5k** [comment]
Copy the updated build from the Siraat package.json and add it in your app and try building it

**Comment by kody435** [comment]
<img width="803" alt="Screenshot 2024-09-18 at 15 34 00" src="https://github.com/user-attachments/assets/2447f3c7-fb3f-4c4a-9397-9e014dce7af6">
When I installed my app, I am getting hit with this error.

**Comment by kody435** [comment]
I am running `npm run electron:dist`

**Comment by kody435** [comment]
@spa5k I copied the update package.json from siraat but still shows the same error as above 👆

**Comment by spa5k** [comment]
Then no idea.

**Comment by spa5k** [comment]
This error is saying that you need to allow it, so allow it.

**Comment by kody435** [comment]
@spa5k Does this generally works for everybody using mac or no?

**Comment by spa5k** [comment]
It's just electron app. Try running it from terminal, you'll see if it gives error

**Comment by kody435** [comment]
wdym, how do I run it in terminal? Please give command to run it. I might be using wrong commands

**Comment by spa5k** [comment]
You basically just need to trigger the binary wherever extracted installer file is, at least it works in linux.

**Comment by kody435** [comment]
It's not giving software setup or installer. Everything other than that is working fine.

**Comment by kody435** [comment]
@spa5k How can I change the name of software? It's not changing even after I export it
<img width="492" alt="Screenshot 2024-09-18 at 16 31 01" src="https://github.com/user-attachments/assets/0ae3df5f-f04b-4144-bd82-a4c034d2b0a9">

**Comment by spa5k** [comment]
https://github.com/spa5k/nextjs_approuter_electron/issues/3

**Comment by kody435** [comment]
> It's not giving software setup or installer. Everything other than that is working fine.

@spa5k

**Comment by spa5k** [comment]
Unfortunately can't help you in this anymore. No Mac in hand.

**Comment by kody435** [comment]
It's actually not generating for windows too.

> Unfortunately can't help you in this anymore. No Mac in hand.

**Comment by spa5k** [comment]
It works in windows, i recently installed it.

**Comment by kody435** [comment]
> #3

Didn't work any of those, any other way to do it?
