### ISSUE TITLE
Shipped my App with Prisma but in Production Unable to Start

### ISSUE THREAD

**Issue by Revaycolizer** [spa5k/nextjs_approuter_electron#11]
I Shipped my App with Prisma built my app and tried running the build of next with electron it worked but after building in production i got Internal Server Error

**Comment by spa5k** [comment]
Try running the packaged app from dist through terminal, you will find the error hopefully

**Comment by Revaycolizer** [comment]
> Try running the packaged app from dist through terminal, you will find the error hopefully

I am getting this error even though i added prisma node_modules on asr and asr unpack

 ⨯ Error: Cannot find module '.prisma/client/default'
Require stack:
- /home/revaycolizer/.local/share/Trash/files/dist/linux-unpacked/resources/app.asar/node_modules/@prisma/client/default.js
- /home/revaycolizer/.local/share/Trash/files/dist/linux-unpacked/resources/app.asar/app/.next/server/app/liked/page.js
- /home/revaycolizer/.local/share/Trash/files/dist/linux-unpacked/resources/app.asar/node_modules/next/dist/server/require.js
- /home/revaycolizer/.local/share/Trash/files/dist/linux-unpacked/resources/app.asar/node_modules/next/dist/server/next-server.js
- /home/revaycolizer/.local/share/Trash/files/dist/linux-unpacked/resources/app.asar/node_modules/next/dist/server/next.js
- /home/revaycolizer/.local/share/Trash/files/dist/linux-unpacked/resources/app.asar/node_modules/next/dist/server/lib/start-server.js
- /home/revaycolizer/.local/share/Trash/files/dist/linux-unpacked/resources/app.asar/build/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1152:15)
    at s._resolveFilename (node:electron/js2c/browser_init:2:121381)
    at /home/revaycolizer/.local/share/Trash/files/dist/linux-unpacked/resources/app.asar/node_modules/next/dist/server/require-hook.js:55:36
    at Module._load (node:internal/modules/cjs/loader:993:27)
    at c._load (node:electron/js2c/node_init:2:17025)
    at Module.require (node:internal/modules/cjs/loader:1240:19)
    at mod.require (/home/revaycolizer/.local/share/Trash/files/dist/linux-unpacked/resources/app.asar/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/revaycolizer/.local/share/Trash/files/dist/linux-unpacked/resources/app.asar/node_modules/@prisma/client/default.js:2:6)
    at Module._compile (node:internal/modules/cjs/loader:1373:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/revaycolizer/.local/share/Trash/files/dist/linux-unpacked/resources/app.asar/node_modules/@prisma/client/default.js',

**Comment by spa5k** [comment]
Look into how you can package prisma in electron, then you should know. What we're doing is nothing special

**Comment by Revaycolizer** [comment]
> Look into how you can package prisma in electron, then you should know. What we're doing is nothing special 

Thanks as currently I see that the major file is omitted .prisma file, let me figure it out as asar is omitting files with .dot

**Comment by spa5k** [comment]
So do you mind adding solution/explanation for the general public?

**Comment by Revaycolizer** [comment]
> So do you mind adding solution/explanation for the general public?

First i had to copy my development db as on development running npx via exec so i had to ship my dev.db during initial start up it will check and create if the db is not found and also to make sure that my libquery is required properly using the correct path

```
function ensureDatabase() {

  if (!fs.existsSync(targetDbPath)) {

    fs.copyFileSync(sourceDbPath, targetDbPath);
  }


  process.env.DATABASE_URL = `file:${targetDbPath}`;
}
const createMigration = () => {
  const randomNumber = Math.floor(Math.random() * 1000000); 
  const migrationName = `migration_${randomNumber}`; 

  const command = `npx prisma migrate dev --name ${migrationName} --schema=${process.env.PRISMA_SCHEMA_PATH}`;

  exec(command, { cwd: path.join(app.getPath('userData')) }, (error, stdout, stderr) => {
    if (error) {
      console.error(`Error creating migration: ${stderr}`);
      return;
    }
    console.log(`Migration created successfully: ${stdout}`);
    
    runMigrations();
  });
};

const runMigrations = () => {
  const command = `npx prisma migrate deploy --schema=${process.env.PRISMA_SCHEMA_PATH}`;

  exec(command, { cwd: path.join(app.getPath('userData')) }, (error, stdout, stderr) => {
    if (error) {
      console.error(`Error deploying migrations: ${stderr}`);
      return;
    }
    console.log(`Migrations deployed successfully: ${stdout}`);
  });
};

app.whenReady().then(() => {
  ensureDatabase()
  createMigration()
  createWindow();

  ipcMain.on("ping", () => console.log("pong"));
  app.on("activate", () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow();
  });
});
```

Also i had to change my schema.prisma a little to change output directory and include binary

```
generator client {
  provider = "prisma-client-js"
  output   = "../src/myprisma/client"
   binaryTargets = ["native", "debian-openssl-3.0.x"]
}

datasource db {
  provider = "sqlite"
  url      = "file:../packages/db/prisma/dev.sqlite"
}
```

Also i ensured that during packing my app using asar to use extraResource so as to make my prisma available

```
 "build": {
    "asar": true,
    "executableName": "NovaPlayer",
    "appId": "com.nova.player",
    "asarUnpack": [
      "node_modules/myprisma/**/*",
      "node_modules/@prisma/client",
      "node_modules/prisma/**/*",
      "node_modules",
      "node_modules/@img",
      "node_modules/sharp",
      ".prisma/**/*",
       "**/.prisma/**/*",
        "**/*.sqlite",
      "**\\*.{node,dll}"
    ],
    "files": [
      "build",
      "prisma",
      "public",
      "node_modules/myprisma/**/*",
      "node_modules/@prisma/client/**/*",
        "src/myprisma/client/prisma.schema",
      "node_modules/prisma/**/*",
       ".prisma/**/*",
       ".env",
      {
        "from": ".next/standalone",
        "to": "app",
        "filter": [
         
          "!**/package.json"
        ]
      },
      {
        "from": ".next/static",
        "to": "app/.next/static"
      },
      {
        "from": "public",
        "to": "app/public"
      }
    ],
    "extraResources": [
      {
        "from": "node_modules/myprisma",
        "to": "app.asar.unpacked/node_modules/myprisma"
      },
      {
        "from": "src/myprisma",
        "to": "app.asar.unpacked/myprisma"
      },
      {
        "from": "src/myprisma/client/dev.db",
        "to": "packages/db/prisma/dev.sqlite"
      }
    ],
    "win": {
      "target": [
        "nsis"
      ]
    },
    "linux": {
      "icon": "public/icons/icons/png",
      "target": [
        "deb"
      ],
      "category": "Development"
    }
  }
}
```

Also in my prisma client I imported it from my output folder and not from PrismaClient
```
import { PrismaClient } from "../src/myprisma/client"

declare global {
  var prisma: PrismaClient | undefined
}

const client = globalThis.prisma || new PrismaClient({
  datasources: {
    db: {
      url: process.env.DATABASE_URL,
    },
  },
})
if (process.env.NODE_ENV !== "production") globalThis.prisma = client

export default client
```
