### ISSUE TITLE
App closing automatically

### ISSUE THREAD

**Issue by devpateltech007** [spa5k/nextjs_approuter_electron#12]
My app keeps closing automatically, after building a windows x64 app. There are no build errors and I have used the same code as mentioned in  [this article](https://www.saybackend.com/blog/03-electron-nextjs-ssr/)

**Comment by spa5k** [comment]
¯\_(ツ)_/¯ It doesn't happen to me, something is crashing in your code, try to debug it. I can't guess with just this much info.

**Comment by devpateltech007** [comment]
is the project supposed to be in some exact file structure for it to work?

**Comment by spa5k** [comment]
you need v to provide more info.

**Comment by devpateltech007** [comment]
Sure, 

My NextJS file structure looks like this 

![image](https://github.com/user-attachments/assets/36cf4351-c98b-4847-a7a7-808cc71bdf52)

On running the app from dist\win-unpacked in cmd as "app.exe" --log I get the following logs

![image](https://github.com/user-attachments/assets/ef6f920d-8c7f-4ec1-b6ec-08603ac0e74d)


Here is the **package.json**
`import { is } from "@electron-toolkit/utils";
import { app, BrowserWindow, ipcMain } from "electron";
import { getPort } from "get-port-please";
import { startServer } from "next/dist/server/lib/start-server.js";
import { join } from "path";
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const createWindow = () => {
  const mainWindow = new BrowserWindow({
    width: 900,
    height: 670,
    webPreferences: {
      preload: join(__dirname, "preload.js"),
      nodeIntegration: true,
    },
  });

  mainWindow.on("ready-to-show", () => mainWindow.show());

  const loadURL = async () => {
    if (is.dev) {
      mainWindow.loadURL("http://localhost:3000");
    } else {
      try {
        const port = await startNextJSServer();
        console.log("Next.js server started on port:", port);
        mainWindow.loadURL(`http://localhost:${port}`);
      } catch (error) {
        console.error("Error starting Next.js server:", error);
      }
    }
  };

  loadURL();
  return mainWindow;
};

const startNextJSServer = async () => {
  try {
    const nextJSPort = await getPort({ portRange: [30_011, 50_000] });
    const webDir = join(app.getAppPath(), "app");

    await startServer({
      dir: webDir,
      isDev: false,
      hostname: "localhost",
      port: nextJSPort,
      customServer: true,
      allowRetry: false,
      keepAliveTimeout: 5000,
      minimalMode: true,
    });

    return nextJSPort;
  } catch (error) {
    console.error("Error starting Next.js server:", error);
    throw error;
  }
};

app.whenReady().then(() => {
  createWindow();

  ipcMain.on("ping", () => console.log("pong"));
  app.on("activate", () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow();
  });
});

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") app.quit();
});

`

**main.js**

`import { is } from "@electron-toolkit/utils";
import { app, BrowserWindow, ipcMain } from "electron";
import { getPort } from "get-port-please";
import { startServer } from "next/dist/server/lib/start-server.js";
import { join } from "path";
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const createWindow = () => {
  const mainWindow = new BrowserWindow({
    width: 900,
    height: 670,
    webPreferences: {
      preload: join(__dirname, "preload.js"),
      nodeIntegration: true,
    },
  });

  mainWindow.on("ready-to-show", () => mainWindow.show());

  const loadURL = async () => {
    if (is.dev) {
      mainWindow.loadURL("http://localhost:3000");
    } else {
      try {
        const port = await startNextJSServer();
        console.log("Next.js server started on port:", port);
        mainWindow.loadURL(`http://localhost:${port}`);
      } catch (error) {
        console.error("Error starting Next.js server:", error);
      }
    }
  };

  loadURL();
  return mainWindow;
};

const startNextJSServer = async () => {
  try {
    const nextJSPort = await getPort({ portRange: [30_011, 50_000] });
    const webDir = join(app.getAppPath(), "app");

    await startServer({
      dir: webDir,
      isDev: false,
      hostname: "localhost",
      port: nextJSPort,
      customServer: true,
      allowRetry: false,
      keepAliveTimeout: 5000,
      minimalMode: true,
    });

    return nextJSPort;
  } catch (error) {
    console.error("Error starting Next.js server:", error);
    throw error;
  }
};

app.whenReady().then(() => {
  createWindow();

  ipcMain.on("ping", () => console.log("pong"));
  app.on("activate", () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow();
  });
});

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") app.quit();
});

`
**preload.js**

`'use strict';

var electron = require('electron');

// electron/preload.ts
electron.contextBridge.exposeInMainWorld("electron", {
  ipcRenderer: {
    send: (channel, data) => electron.ipcRenderer.send(channel, data),
    on: (channel, listener) => electron.ipcRenderer.on(channel, listener)
  }
});
`

I hope I am not missing out on any useful info to figure this out, if I did please let me know

**Comment by spa5k** [comment]
Looks like you have changed the file structure, copy as it is. check https://github.com/spa5k/GreenDome/ for a more complete sample

**Comment by spa5k** [comment]
Any update on? Will close the issue otherwise

**Comment by devpateltech007** [comment]
I am trying again with different config and will update in 12 hours max, thanks for your patience

**Comment by spa5k** [comment]
No update, closing it.
