### ISSUE TITLE
Better compatibility

### ISSUE THREAD

**Issue by dnnsjsk** [spa5k/nextjs_approuter_electron#2]
Hey,

this boilerplate helped me tremendously with my first exploration into packaging a Next.js app with Electron. However, I always got an error when moving the App to a different location like desktop. (I'm using mac)

I think it has to do with path resolving of modules like `sharp`, which result in a fatal error if you are using the package in an API route or Server Action. I've done following changes to the setup to fix those issues:

Change webdir path in main.js
```js
const webDir = path.join(app.getAppPath(), "app");
```

Move extra_files to files:
```json
    "files": [
      "main",
      {
        "from": ".next/standalone",
        "to": "app",
        "filter": [
          "!**/.env",
          "!**/package.json"
        ]
      },
      {
        "from": ".next/static",
        "to": "app/.next/static"
      },
      {
        "from": "public",
        "to": "app/public"
      }
    ]
```

Unpack next in `asarUnpack`:
```json
    "asarUnpack": [
      "node_modules/next"
    ],
```

If you're using `sharp`:
```json
    "asarUnpack": [
      "node_modules/next",
      "node_modules/@img",
      "node_modules/sharp"
    ],
```

This also packages the Next export inside the `.asar` archive.

Maybe this'll help someone else! :-)

**Comment by spa5k** [comment]
Thanks a lot, I tried packing the Next.js inside asar archive, but it wasn't working well in the past.

If it works nicely, I will update the main branch
