### ISSUE TITLE
next-server showing in menu bar

### ISSUE THREAD

**Issue by dnnsjsk** [spa5k/nextjs_approuter_electron#3]
![PixelSnap 2024-07-15 at 15 32 46@2x](https://github.com/user-attachments/assets/d8c3f01d-679c-4e55-afc0-c7bd0fa7c032)

I can't seem to fix this! It seems like the `productName` is being overwritten by the Next server.

**Comment by spa5k** [comment]
Not sure, you will probably need to custom hack it or something

**Comment by spa5k** [comment]
You can override it using the Next.js utilities, or normal head tag, title tag


https://nextjs.org/docs/app/building-your-application/optimizing/metadata

```ts
import type { Metadata } from 'next'
 
export const metadata: Metadata = {
  title: '...',
  description: '...',
}
 
export default function Page() {}
```

Report again if this does not fix it.

**Comment by dnnsjsk** [comment]
Had to set it manually after starting the server:

```js
await startServer({
        dir: webDir,
        isDev: false,
        hostname: "localhost",
        port: nextJSPort,
        customServer: true,
        allowRetry: false,
      });
      process.title = "OneClick Pro";
```
