### ISSUE TITLE
Question: dev mode, simplicity

### ISSUE THREAD

**Issue by nandorojo** [spa5k/nextjs_approuter_electron#5]
Hey! Thanks **so much** for publishing this.

Quick questions:

1. Readme states "Electron expects that you have already created production output of the NextJS app"

How could we make this support local dev mode/HMR? I'm trying to get that spun up. Should that work with `make web dev`? 

2. Is it necessary to even copy the files? Couldn't `startServer` just get the path to `../web` directly without copying any files?

3. Calling `make web dev` throws this error for me. I wonder if there might be a simpler script that could do it.

I'll be poking around to see if I can address these things, so I wanted to share them first. Thank you!
<img width="335" alt="Screenshot 2024-07-25 at 7 26 21 AM" src="https://github.com/user-attachments/assets/3ca3f446-dd71-4355-9e44-c8875f4e52ad">

**Comment by nandorojo** [comment]
For dev mode, I just called `npm run dev` in `web` and `npm run dev` in `electron` (in a separate terminal) and it worked fine.

Going to see if I can generally get rid of the file copying

**Comment by spa5k** [comment]
In dev mode, you don't need to copy or anything, you can just the electron and the Next.js server on another terminal. What I stated is for build time.

**Comment by nandorojo** [comment]
Yeah got it working now, makes sense, dev mode works fine for me. Thanks!

**Comment by spa5k** [comment]
@nandorojo now I've updated it to a normal repo, you don't need to copy when it comes to production mode anymore. It works directly and is much simpler.
