### ISSUE TITLE
MacOs Unable to run the packaged app. 

### ISSUE THREAD

**Issue by kody435** [spa5k/nextjs_approuter_electron#7]
I am trying to find a way to log the errors I am getting on Runtime. I can't even see what the error is and I am just guessing should be making error?

https://github.com/user-attachments/assets/f2b534fb-97d3-4a02-853a-b9f94a7f9409

**Comment by spa5k** [comment]
Run it like this from terminal https://www.wikihow.com/Open-Applications-Using-Terminal-on-Mac

**Comment by kody435** [comment]
@spa5k Can you help me in making a new setup or template which I can use without any need to solve things.

**Comment by spa5k** [comment]
Nah no time and no mac, you can check the Siraat app on how you can make the installer, rest is upto you

**Comment by spa5k** [comment]
Just check the github action and taskfile there.

**Comment by kody435** [comment]
> Just check the github action and taskfile there.
> 
> https://github.com/spa5k/siraat

Ok, So now it seems to be able to make installed and all versions. How can I reduce the overall size of bundle. It's getting around 500MB+

**Comment by kody435** [comment]
<img width="456" alt="Screenshot 2024-09-18 at 21 36 04" src="https://github.com/user-attachments/assets/3c99c0e1-3a38-4cc1-a2dc-26be5ff19a3f">

@spa5k It's not showing any errors at all

**Comment by spa5k** [comment]
No idea.

**Comment by spa5k** [comment]
For the size, it's coming this big because it's making it for every platform in one go, if you check again, you'll see how to bundle it separately for every platform, so if you run those commands separately it'll be less size

**Comment by kody435** [comment]
> For the size, it's coming this big because it's making it for every platform in one go, if you check again, you'll see how to bundle it separately for every platform, so if you run those commands separately it'll be less size

Ok, Gotcha

**Comment by kody435** [comment]
@spa5k Is there any way we can export and distribute apps to MacOS users without needing Apple Developer Id?

**Comment by spa5k** [comment]
No idea

**Comment by kody435** [comment]
And what about source code protection?

**Comment by kody435** [comment]
@spa5k 

> And what about source code protection?

**Comment by spa5k** [comment]
Don't ask generic electron questions here.
