### ISSUE TITLE
How to use next-auth?

### ISSUE THREAD

**Issue by Mebius1916** [spa5k/nextjs_approuter_electron#8]
Hello, this example does not seem to support next-auth. I used next-auth on this example and it can start normally. However, after packaging it into an application, it will show that next-auth cannot connect normally. I want to know what the problem is.

**Comment by spa5k** [comment]
No idea, this is just a template, rest needs to be checked and fixed yourself.

**Comment by notwatermango** [comment]
Tried iron session too, not working.

**Comment by Mebius1916** [comment]
> 也尝试了 iron 会话，不起作用。

Now I gave up using next's ssr in electron. I extracted the next part of nextron into a web page and packaged it with pake, which solved my needs.

**Comment by spa5k** [comment]
The problem is likely happening with the redirect URLs and how you are storing it, it's doing nothing new, the server is still running etc, in order to send the callbacks to electron, you will need to implement electron direct URL, then it can work.

**Comment by spa5k** [comment]
Also why will you be setting up the backend in the electron itself since it will run locally, if you want to save cookies etc, then it can work normally

**Comment by notwatermango** [comment]
I successfully got iron-session working. One of the issues was that the server couldn't read the environment variables. That one issue I cannot fix, so I hardcode the secret for now since it's a private internal tool.

**Comment by spa5k** [comment]
How about sharing the solution here, at least in minimal details for future people

**Comment by notwatermango** [comment]
By writing the secrets without using env
